wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.4
    start_time: 1643920287
    t:
      1:
      - 1
      - 3
      - 5
      2:
      - 1
      - 3
      - 5
      3:
      - 16
      4: 3.6.4
      5: 0.12.10
      8:
      - 5
test string:
  desc: null
  value: hello world
value:
  desc: null
  value: 0.5
